roles/virtcontroller/templates/virt_ui.yml.j2

The nginx server in the UI pod is actually listening on port 8080, so the UI is inaccessible when using 9000 in pod and service spec. This pull request changes the ports to 8080.

Change UI port to 8080

---

deploy/olm-catalog/bundle/manifests/konveyor-virt-operator.v99.0.0.clusterserviceversion.yaml

- Fix #18
See sample clusterrole bound to virt-controller sa below : 
```
oc describe clusterrole konveyor-virt-operator.v99.0.0-964458977
Name:         konveyor-virt-operator.v99.0.0-964458977
Labels:       olm.owner=konveyor-virt-operator.v99.0.0
olm.owner.kind=ClusterServiceVersion
olm.owner.namespace=openshift-migration
operators.coreos.com/virt-operator.openshift-migration=
Annotations:  <none>
PolicyRule:
Resources                                       Non-Resource URLs  Resource Names  Verbs
---------                                       -----------------  --------------  -----
*.virt.konveyor.io                              []                 []              [*]
secrets                                         []                 []              [get list watch create update patch …
```

virt-controller: RBAC allow get/list namespaces

---

roles/virtcontroller/templates/virt_ui_route.yml.j2

Follow-up of https://github.com/konveyor/virt-operator/pull/14 to use the right port in the route.

Fix UI route to point to port-8080

---

roles/virtcontroller/templates/virt_ui.yml.j2

When the user connects to the UI, the following error is thrown:
```
{
"message": "request+to+https://api.cluster-test.example.com:6443/.well-known/oauth-authorization-server+failed,+reason:+self+signed+certificate+in+certificate+chain",
"type": "system",
"errno": "SELF_SIGNED_CERT_IN_CHAIN",
"code": "SELF_SIGNED_CERT_IN_CHAIN"
}
```
Obviously, this is due to the fact that the OpenShift cluster is deployed with self-signed certificates, and NodeJS refuses to use insecure connection. However, to allow consuming the API from applications, the cluster mounts the self-signed CA chain in all the pods in the hard coded path `/var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt`.
This pull request adds the [`NODE_EXTRA_CA_CERTS`](https://nodejs.org/api/cli.html#cli_node_extra_ca_certs_fil …

Add services CA certs to virt-ui deployment environment

---

deploy/olm-catalog/bundle/manifests/konveyor-virt-operator.v99.0.0.clusterserviceversion.yaml
roles/virtcontroller/templates/virt_controller_rbac.yml.j2

To be able to run a migration, the `virt-controller` role needs to be extended with the following permissions:
- `namespaces` - `any` - It allows `virt-controller` to create the target namespace if it doesn't exist.
- `resourcemappings`, `virtualmachineimports` - `any` - It allows `virt-controller` to manage the VMIO resources.
- `datavolumes` - `read` - It allows `virt-controller` to monitor the disks transfer directly from the Data Volumes.
Fixes #23

Extend virt-controller cluster role

---

virt-operator-bundle.yaml

Enhancement : 
* Allows an updateStrategy set to poll every 10 minutes for catalogsource updates, requires marketplace operator monitoring for updates.
See references here : 
https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/catalog-polling.md
https://docs.openshift.com/container-platform/4.5/rest_api/operatorhub_apis/catalogsource-operators-coreos-com-v1alpha1.html

catalogsource: Implement updateStrategy

---

roles/virtcontroller/templates/virt_ui.yml.j2
roles/virtcontroller/templates/virt_ui_route.yml.j2

This pull request is a companion for [konveyor/virt-ui#172](https://github.com/konveyor/virt-ui/pull/172). The goal is to enable TLS for the UI container, also for internal traffic.
- An annotation is added to the service to get a secret named `migration-ui-tls` with a certificate/key pair generated by openshift-service-serving-signer.
- The secret is mounted in `/var/run/secrets/migration-ui-tls`.
- The service and container ports are changed to 8443.
- The route is changed to reencrypt traffic from external clients ; internal clients also have the CA chain as `/var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt`.
More information on using service serving certificates is available at [OpenShift > Security and compliance > Configuring certificates > Securing service traffic using …

Enable TLS for UI

---

roles/virtcontroller/templates/virt_controller.yml.j2

This is a follow-up for https://github.com/konveyor/virt-controller/pull/41, because the path of the `manager` command is now `/usr/local/bin/manager`.

Update virt-controller containers command

---

deploy/olm-catalog/bundle/manifests/konveyor-virt-operator.v99.0.0.clusterserviceversion.yaml

* Require a minimum 1.9.0 (OCP 4.6) release for MTV deployments, aligns with the minimum pre-reqs for MTV. (CNV)
* Clusters older than 4.6 will show a pending installation with a requirements not met message
* Minor tweaks to description

OLM: Implement minKubeVersion

---

roles/virtcontroller/vars/main.yml

With [konveyor/virt-ui#214](https://github.com/konveyor/virt-ui/pull/214), the UI uses internal service URLs to reach OpenShift API, inventory and inventory payload services. Rather than using hard coded values, the UI should use variables exposes in virtMeta.json file. This pull request updates the values in this file to point to internal services.

Use internal service URLs

---

roles/virtcontroller/templates/inventory.yml.j2
roles/virtcontroller/templates/virt_controller.yml.j2

This pull request is a companion for [konveyor/controller#29](https://github.com/konveyor/controller/pull/29), [konveyor/virt-controller#79](https://github.com/konveyor/virt-controller/pull/79). The goal is to enable TLS for the inventory container, also for internal traffic.
- An annotation is added to the service to get a secret name `inventory-tls` with a certificate/key pair generated by openshift-service-serving-signer.
- The secret is mounted in `/var/run/secrets/inventory-tls`.
- The service and container ports are changed to 8443.
- The route is changed to reencrypt traffic from external clients ; internal clients also have the CA chain as `/var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt`.
More information on using service serving certificates is available at …

Enable TLS for inventory

---

roles/virtcontroller/templates/inventory_payload.yml.j2
roles/virtcontroller/vars/main.yml

This is a follow-up PR for https://github.com/konveyor/virt-payload/pull/10. It does the following things:
- Annotate the `inventory-payload` service to generate the secret with TLS cert/key.
- Mount the secret in the `inventory-payload` pod.
- Pass the `API_TLS_CERTIFICATE` and `API_TLS_KEY` environment variable to the pod to enable TLS in Sinatra.
- Update pod and service ports to 8443.
- Update the route to reencrypt traffic.
- Update the UI config to use the new inventory payload URL.
Fixes https://github.com/konveyor/virt-payload/issues/12.

Enable TLS for inventory-payload

---

roles/virtcontroller/templates/virt_controller.yml.j2

This pull request adds that `API_TLS_ENABLED` environment variable to the `main` and `inventory` containers of the `virt-controller` pod. It also adds the `API_PORT` environment variable to the `main` container. This way, the inventory client (`main`) know how to connect to the inventory server (`inventory`).
And because the certificate used is signed for `inventory.<virt_namespace>.svc` and `inventory.<virt_namespace>.svc.cluster.local`, the `API_HOST` is also added to the `main` container, so that the certificate validation succeeds.

Pass environment variables to enable TLS in inventory client

---

requirements.yml

During cleanup, I was a bit too eager and removed `requirements.yml` which is required by the operator.

Restore requirements.yml

---

roles/forkliftcontroller/templates/configmap-ui.yml.j2
roles/forkliftcontroller/templates/oauthclient-ui.yml.j2

The oAuth client id for the UI is the UI service name. Fixing it in meta.json file.
Also, the redirectURLs need to have `.apps`.

Fix UI oAuth config

---

build/Dockerfile
requirements.yml

The operator-framework/ansible-operator:v1.2.0 base image already prepares the environment.
However, to remain as close as possible to the registry.redhat.io/openshift-4/ose-ansible-operator:v4.6 image, we need to override the collections versions: `community.kubernetes:0.11.1` and `operator_sdk.util:0.0.0`.
The other RPMs are not needed in the context of Forklift, as we don't interact with AWS.

Bump base image to 1.2.0 and clean

---

build/Dockerfile
roles/forkliftcontroller/tasks/main.yml

To match the OpenShift 4.6 setup, this pull request rebases the container on operator-sdk v0.19.4.
Since Ansible 2.9 and the introduction of collections, the `k8s_facts` module is replaced by `k8s_info`. This pull request also replaces all the calls to `k8s_facts` with `k8s_info`.

Rebase base image to v0.19.4

---

deploy/olm-catalog/bundle/manifests/konveyor-forklift-operator.v2.0.0-beta.0.clusterserviceversion.yaml

This fixes allows proper SDK validation of version on the CVS spec, also updated operator image to use beta release.

OLM: fix CVS version string

---

roles/forkliftcontroller/templates/deployment-controller.yml.j2

With https://github.com/konveyor/forklift-controller/pull/131, we can set the port for the metrics service in the inventory container. To avoid port conflict, we set it to 8081, while the controller container will use the default 8080 port.

Add environment variable for metrics port in controller pod

---

roles/forkliftcontroller/tasks/main.yml
roles/forkliftcontroller/templates/configmap-ui.yml.j2
roles/forkliftcontroller/templates/oauthclient-ui.yml.j2

With [BZ#1813012](https://bugzilla.redhat.com/show_bug.cgi?id=1813012), the `etcdDiscoveryDomain` attribute of the `cluster` infrastructure is not set by the OpenShift installer. The consequence is that the `cluster_dns_suffix` is empty and then the redirect URL for the OAuthClient CR is incomplete.
Moreover, Kubernetes doesn't have the `Infrastructure` kind, which is part of the `config.openshift.io/v1` API, so this configuration mechanism is not available in a Kubernetes cluster.
This pull request restores the previous mechanism. We create the UI route earlier, as it is the one we need for the redirect URL. Then, we retrieve the Route object and extract the FQDN from its spec.

Get UI FQDN from route instead of infrastructure

---

README.md
deploy/olm-catalog/bundle/manifests/konveyor-forklift-operator.v99.0.0.clusterserviceversion.yaml
roles/forkliftcontroller/defaults/main.yml

Since this project should not be limited to OpenShift, this pull request renames the default namespace to `konveyor-forklift`.
It also better reflects the community the project belongs to.

Rename the default namespace to konveyor-forklift

---

roles/forkliftcontroller/defaults/main.yml
roles/forkliftcontroller/templates/deployment-controller.yml.j2

* Fixes #88 
* Inject POLICY_AGENT_URL and POLICY_AGENT_SEARCH_INTERVAL to inventory container on controller pod
* validation_policy_agent_search_interval variable controls the search interval in seconds (default 10)
* Please note inventory container policy agent settings/variables are only populated when feature_validation is true (on by default)

Set policy agent url and search interval on inventory container

---

bundle/manifests/konveyor-forklift-operator.v2.0.0.clusterserviceversion.yaml

Picked for release-v2.0.0 , see #92

CSV: Update to require kube v1.20.0 as minimum

---

bundle/manifests/konveyor-forklift-operator.v99.0.0.clusterserviceversion.yaml
docs/README.md
roles/forkliftcontroller/defaults/main.yml
roles/forkliftcontroller/tasks/main.yml
roles/forkliftcontroller/templates/deployment-ui.yml.j2
tools/cut-release.yml

- Fetch and expose OCP ClusterVersion from config API on container using the FORKLIFT_CLUSTER_VERSION env variable, it targets the latest completed version running on the cluster 
- Set a role var indicating the operator version and also expose to UI via FORKLIFT_OPERATOR_VERSION
- RBAC updates
- Documentation and release scripts update
- Fixes #94 
- Tested on OCP v4.7
Sample env from UI container : 
```
Environment:
META_FILE:                  /etc/forklift-ui/meta.json
NODE_EXTRA_CA_CERTS:        /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt
FORKLIFT_OPERATOR_VERSION:  latest
FORKLIFT_CLUSTER_VERSION:   4.7.3
```

UI: Expose OCP and forklift versions

---

roles/forkliftcontroller/tasks/main.yml

Cleanup leftover k8s_facts calls from forkliftcontroller role

Remove legacy k8s_facts calls from ansible role

---

bundle/manifests/forklift.konveyor.io_forkliftcontrollers.yaml
config/crd/bases/forklift.konveyor.io_forkliftcontrollers.yaml

Current CRD spec validation ignores CR customizations as unknown fields are not being preserved, only declared properties , this reverts the behavior and allows again customizing all variables (images, etc) within the CR.

Fix regression in spec validation for forkliftcontrollers CRD

---

roles/forkliftcontroller/tasks/main.yml
roles/forkliftcontroller/templates/configmap-controller.yml.j2
roles/forkliftcontroller/templates/configmap-ui.yml.j2

This PR removes all k8s calls to manage status manually in favor of ansible operator builtin managed status, we don't have any need to modify status manually in reconcile loop since we deploy in OCPv4 clusters where managed status is supported. Also, added labels to our configmaps to detail what service they belong to for consistency reasons.

Operator: remove manually managed status

---

PROJECT
bundle/manifests/forklift.konveyor.io_forkliftcontrollers.yaml
bundle/manifests/forklift.konveyor.io_hooks.yaml
bundle/manifests/forklift.konveyor.io_hosts.yaml
bundle/manifests/forklift.konveyor.io_migrations.yaml
bundle/manifests/forklift.konveyor.io_networkmaps.yaml
bundle/manifests/forklift.konveyor.io_plans.yaml
bundle/manifests/forklift.konveyor.io_providers.yaml
bundle/manifests/forklift.konveyor.io_provisioners.yaml
bundle/manifests/forklift.konveyor.io_storagemaps.yaml
bundle/manifests/konveyor-forklift-operator.v99.0.0.clusterserviceversion.yaml
config/crd/bases/forklift.konveyor.io_forkliftcontrollers.yaml
config/rbac/role.yaml
config/samples/forklift_v1beta1_forkliftcontroller.yaml
config/samples/kustomization.yaml
molecule/default/tasks/forkliftcontroller_test.yml
roles/forkliftcontroller/templates/provider-host.yml.j2
roles/forkliftcontroller/templates/provisioner-aws-ebs.yml.j2
roles/forkliftcontroller/templates/provisioner-azure-disk.yml.j2
roles/forkliftcontroller/templates/provisioner-azure-file.yml.j2
roles/forkliftcontroller/templates/provisioner-cinder.yml.j2
roles/forkliftcontroller/templates/provisioner-gce-pd.yml.j2
roles/forkliftcontroller/templates/provisioner-hostpath-provisioner.yml.j2
roles/forkliftcontroller/templates/provisioner-manila.yml.j2
roles/forkliftcontroller/templates/provisioner-openshiftstorage.cephfs.csi.ceph.com.yml.j2
roles/forkliftcontroller/templates/provisioner-openshiftstorage.rbd.csi.ceph.com.yml.j2
roles/forkliftcontroller/templates/provisioner-rbd.yml.j2
roles/forkliftcontroller/templates/provisioner-vsphere-volume.yml.j2
watches.yaml

Forklift API is promoted to `v1beta1`. This pull request updates the CRDs and all other references.

Update CRDs to v1beta1 API version

---

bundle/manifests/konveyor-forklift-operator.v99.0.0.clusterserviceversion.yaml
roles/forkliftcontroller/defaults/main.yml
roles/forkliftcontroller/templates/deployment-controller.yml.j2

This PR adds settings support for profiling and logging into the controller pod, settings can be injected into the forkliftcontroller CR spec, by default they are unset/disabled. The following environmental variables would be exposed to both containers in the controller pod when set: 
```
LOG_LEVEL: Set the verbosity.
PROFILE_KIND: Kind of profile (memory|cpu|mutex).
PROFILE_PATH: Profiler output directory.
PROFILE_DURATION: The duration (minutes) the profiler will collect data. (0=indefinitely)
```
- New logging and profiling operator variables are the following :  controller_log_level , controller_profile_kind , controller_profile_path , controller_profile_duration
- Variables have no default
- controller_log_level must be set and be of type integer to trigger an update on the …

Add logging and profiler settings to controller

---

roles/forkliftcontroller/templates/deployment-controller.yml.j2

Downstream operator image is based uses Jinja 2.10 that doesn't support the `integer` test. This is only available starting with 2.11. In the version 2.10, the `number` test is available, so this pull request changes the template to use it.

Fix number test in Ansible template

---

bundle/manifests/konveyor-forklift-operator.v99.0.0.clusterserviceversion.yaml
config/samples/forklift_v1beta1_forkliftcontroller.yaml

When installing Forklift, it is painful to have to create the ForkliftController CR manually, when it is actually mandatory.
This pull request adds it as an initialization custom resource [1], so that it's created during the operator installation.
[1] [OpenShift Doc > Operator > Initializing required custom resources
](https://docs.openshift.com/container-platform/4.7/operators/operator_sdk/osdk-generating-csvs.html#osdk-init-resource_osdk-generating-csvs)
RHBZ: https://bugzilla.redhat.com/show_bug.cgi?id=1963682

BZ 1963682 - Create the ForkliftController CR at install time

---

roles/forkliftcontroller/templates/deployment-ui.yml.j2

This pull request is a parallel change to https://github.com/konveyor/forklift-ui/pull/680, in order to point the  `NODE_EXTRA_CA_CERTS` environment variable to `ca.crt`, instead of `service-ca.crt`.

Bug 1977657 - Use ca.crt instead of service-ca.crt for UI

---

roles/forkliftcontroller/templates/deployment-ui.yml.j2

This is a sibling pull request for https://github.com/konveyor/forklift-ui/pull/681 and points `NODE_EXTRA_CA_CERTS` to `/opt/app-root/src/ca.crt`.

Bug 1977657 - Set CA bundle to /opt/app-root/src/ca.crt

---

.github/workflows/csv-validate.yml

This PR adds bundle validation using Operator SDK to prevent issues with malformed manifests on CSV, these are the main rules for the GH action : 
- Only pull requests to master or release-* branches will trigger this action
- Only changes in bundle/* will trigger the action
- Operator SDK version used is the same as the one that built the operator for each respective branch, needs to be updated for each branch i.e (v2.0.0 -> sdk-1.3.2 , v2.1.0 -> sdk-1.8.0)

GH Action: Add CSV validation

---

.github/workflows/ansible-lint.yml

This PR adds an ansible linting GH action workflow to the operator repo, it is intended to catch issues when modifying operator roles.
- Targets main and release branches
- Gates incoming PRs that modify .yml or .yaml files in roles/
- Uses ansible-lint which is an action verified by GH

PR sanity: Add ansible linter GH action

---

bundle/manifests/konveyor-forklift-operator.v99.0.0.clusterserviceversion.yaml

Adjust perms to the forklift-controller SA in order to resolve RBAC issues with hooks, see : https://bugzilla.redhat.com/show_bug.cgi?id=1987479
- Allow manipulation of configmaps
- Allow manipulation of batch/jobs 
Sample cluster role assigned to controller SA : 
```
oc describe clusterrole konveyor-forklift-operator.v99.0.0-6c5d78c585
Name:         konveyor-forklift-operator.v99.0.0-6c5d78c585
Labels:       olm.owner=konveyor-forklift-operator.v99.0.0
olm.owner.kind=ClusterServiceVersion
olm.owner.namespace=konveyor-forklift
operators.coreos.com/forklift-operator.konveyor-forklift=
Annotations:  <none>
PolicyRule:
Resources                                       Non-Resource URLs  Resource Names  Verbs
---------                                       -----------------  -------------- …
```

Bug: 1987479 RBAC fix for hooks

---

roles/forkliftcontroller/defaults/main.yml
roles/forkliftcontroller/tasks/main.yml

As per @jortel request , we are setting a default loglevel of 3 for the controller pod (both containers) instead of relying on 0 (unset).
Please let me know if we should pick this one for 2.1.0.

controller pod: Set and increase default loglevel

---

bundle/manifests/konveyor-forklift-operator.v99.0.0.clusterserviceversion.yaml
roles/forkliftcontroller/tasks/main.yml

- Load API groups in currently running cluster and use it to determine functionality available to operator (routes, cnv, k8s)
- Avoid creating host provider unless API group kubevirt.io is present on the cluster
- Remove unnecessary infrastructure resource access from RBAC

Bug 1965030: Avoid creating host provider if CNV is not installed

---

roles/forkliftcontroller/defaults/main.yml
roles/forkliftcontroller/tasks/cleanup.yml
roles/forkliftcontroller/tasks/main.yml

This PR will ensure we perform cleanups when a particular feature is disabled after initial deployment. Fixes #151 .
- Use state variables to reconcile for features (ui_state , validation_state)
- Implement re-usable cleanup.yml which gets resources by label and removes them

Ensure cleanups when features are disabled on CR

---

roles/forkliftcontroller/templates/deployment-controller.yml.j2

As requested by @jortel , controller container renamed to main on controller pod.

Rename controller container

---

roles/forkliftcontroller/tasks/main.yml

Remove force-disablement of UI on k8s clusters as work on this will be starting during this Forklift release.

Re-enable UI when running on k8s

---

roles/forkliftcontroller/tasks/main.yml

Ensure all non-k8s cluster UI deployment logic is contained within a single block (oauth2/routes). This also provides a safer reconcile order of tasks.
Tested on OCP v4.9 and kube v1.22.0

Enhance non-k8s UI deployment logic

---

bundle/manifests/konveyor-forklift-operator.v99.0.0.clusterserviceversion.yaml
roles/forkliftcontroller/defaults/main.yml
roles/forkliftcontroller/tasks/main.yml
roles/forkliftcontroller/templates/deployment-must-gather-api.yml.j2
roles/forkliftcontroller/templates/service-must-gather-api.yml.j2

The must-gather-api service exposes an API to trigger a must-gather collection, with a target namespace, plan, VM if needed.
This pull request adds the deployment and service to the role. It also updates the CSV to list must-gather-api and virt-v2v images.

Add must-gather-api service

---

bundle/manifests/konveyor-forklift-operator.v99.0.0.clusterserviceversion.yaml
roles/forkliftcontroller/defaults/main.yml
roles/forkliftcontroller/tasks/main.yml
roles/forkliftcontroller/templates/configmap-ui.yml.j2
roles/forkliftcontroller/templates/deployment-must-gather-api.yml.j2
roles/forkliftcontroller/templates/service-must-gather-api.yml.j2

- Cleaned up TLS (disabled by default since GIN gonic needs extra work)
- Use appropiate environment GIN gonic vars for settings
- JSON typo on ALM bundle examples
- Added UI mustGatherApi info to UI configmap
- Other minor syntax issues
- Validated feature cleanup tasks
Tested on OCP v4.9
```
oc logs forklift-must-gather-api-6598bf779f-q5bj5
2021/09/15 18:18:59 Config option DB_PATH set from environment variable to: /tmp/gatherings.db
[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
- using env:	export GIN_MODE=release
- using code:	gin.SetMode(gin.ReleaseMode)
2021/09/15 18:18:59 Config option CLEANUP_MAX_AGE set from environment variable to: …
```

Minor fixes for must-gather-api service

---

roles/forkliftcontroller/defaults/main.yml
roles/forkliftcontroller/templates/deployment-controller.yml.j2

The name of the image used to run virt-v2v is set by default to `quay.io/konveyor/forklift-virt-v2v:latest`.
This pull request allows to set it via an environment variable. And the user can set it via an extra var.
Signed-off-by: Fabien Dupont <fdupont@redhat.com>

Pass the VIRT_V2V_IMAGE variable to the controller container

---

roles/forkliftcontroller/defaults/main.yml
roles/forkliftcontroller/templates/deployment-validation.yml.j2

Add missing validation service constrains , resource consumption sample taken from a QE cluster with a migration load. Fixes #168

Add validation service resource constrains

---

bundle/manifests/forklift.konveyor.io_migrations.yaml
bundle/manifests/forklift.konveyor.io_plans.yaml

- Remove requirement for restorePowerState in migrations and plans CRDs

Bug 2012564: Sync CRDs with #179

---

roles/forkliftcontroller/tasks/main.yml

This PR attempts to rectify issues when upgrading controller from previous releases where the default k8s merge type (stragegic_merge) causes an append to the controller deployment resource instead of updating. This has surfaced via #154 , the symptoms are that the controller pod starts 3 containers (controller, main and inventory) instead of 2 causing resource constrains and further failures.
I'm only targeting the controller deployment since we need more validation to ensure that it is safe and does not introduce side effects or issues.

Change controller k8s module call to non-default merge type

---

roles/forkliftcontroller/defaults/main.yml
roles/forkliftcontroller/templates/configmap-controller.yml.j2
roles/forkliftcontroller/templates/deployment-controller.yml.j2

This PR makes PRECOPY_INTERVAL a managed operator setting: 
* controller_precopy_interval is the controlling forkliftcontrollers spec variable with a default setting of 60
* controller_precopy_interval is injected into the main container in the controller pod
* controller_precopy_interval value must be an integer
* For the sake of consistency, the forklift-controller configmap is also configured with the same controller_precopy_interval , we want to avoid a user mistakenly setting different values (deployment vs configmap)
Sample forkliftcontrollers CR setting below : 
```
Spec:
controller_precopy_interval: 3
feature_ui:                   true
feature_validation:           true
```

Bug 2024153: Make PRECOPY_INTERVAL a managed setting in operator

---

roles/forkliftcontroller/defaults/main.yml
roles/forkliftcontroller/templates/deployment-controller.yml.j2

https://github.com/konveyor/forklift-controller/pull/356 adds the ability to use Change IDs for warm migration, hence to not retain snapshots during warm migration. This feature is disabled by default in the controller, so this pull request enables it by default at the operator level.

Bug 1942651: Enable vSphere incremental backup by default

---

roles/forkliftcontroller/defaults/main.yml
roles/forkliftcontroller/templates/deployment-must-gather-api.yml.j2

We have noticed that the must-gather image used in v2.2.0 deployments is `quay.io/konveyor/forklift-must-gather:latest`, while it should be the image tagged with `release-v2.2.0`. This is because the `DEFAULT_IMAGE` environment is not set on the `forklift-must-gather-api` deployment.
This pull request sets the environment to `MUST_GATHER_IMAGE`, itself set in the CSV to the tag matching the release.
It also deduplicates a section of the deployment template.

Use must gather image envvar

---

roles/forkliftcontroller/templates/deployment-must-gather-api.yml.j2

With https://github.com/konveyor/forklift-must-gather-api/pull/18, the variable `DEFAULT_IMAGE` has been renamed to `MUST_GATHER_IMAGE`. This pull request adjusts the must-gather-api deployment.

Replace DEFAULT_IMAGE with MUST_GATHER_IMAGE

---

roles/forkliftcontroller/tasks/main.yml

We have seen cases where the validation service configmap data was emptied. We suspect that the operator role overrides the data. According to the k8s module documentation, a strategic merge is done and it _should_ retain the files listed in `.data`. Observation in the field is different.
This pull request checks the presence of the controller and validation service configmaps and skips the configmap creation/update if it exists. This should avoid any risk of the operator overriding them when they contain user data.

Bug 2026702: Do not override controller and validation service configmaps

---

roles/forkliftcontroller/defaults/main.yml
roles/forkliftcontroller/templates/deployment-must-gather-api.yml.j2

The must-gather-api service can generate debug messages
when the `DEBUG` environment variable is set to `'true'`.
This change allows setting the `must_gather_api_debug`
boolean on the ForkliftController CR to enable debug
mode. The default value is `'false'` to reduce potential
load on the pod.

Allow setting debug mode for must-gather-api

---

roles/forkliftcontroller/tasks/main.yml
roles/forkliftcontroller/templates/configmap-validation.yml.j2

An empty data dict structure was being set in the config map template for validation, this causes the k8s ansible module with a default merge strategy to reset all data in every reconcile, this PR prevents that behavior and allow users settings to be retained once config map is modified.

Bug 2026702: Do not initialize empty data structure on validation config map

---

roles/forkliftcontroller/tasks/main.yml
roles/forkliftcontroller/templates/configmap-trusted-ca.yml.j2
roles/forkliftcontroller/templates/deployment-ui.yml.j2

In OpenShift, it is possible to configure a custom certificate for the ingress routes. The full CA chain is provided to allow certificate verification. By default, the custom CA chain is not exposed in `/var/run/secrets/kubernetes.io/serviceaccount/ca.crt`, so pods cannot
reach services on their external URL.
The UI uses a callback link with the external URL of the UI, since it will then be passed to the user's browser that can only access external URLs. This forbids the access to the UI when using custom CA.
This change applies the OpenShift documentation [1] to mount the custom CA certificate merged with the other internal CA certificates in the UI pod. This is done by creating an empty ConfigMap annotated with `config.openshift.io/inject-trusted-cabundle="true"` and mounting this …

Bug 1994179: Add support for custom ingress CA chain in OpenShift

---

bundle/manifests/konveyor-forklift-operator.v99.0.0.clusterserviceversion.yaml
roles/forkliftcontroller/tasks/main.yml
roles/forkliftcontroller/templates/deployment-ui.yml.j2

Fixes for #201, it needs RBAC access to proxies, also ensure trusted_ca_enabled is defined when templating.

RBAC: Allow access to proxies resource, related to #201

---

bundle/manifests/konveyor-forklift-operator.v99.0.0.clusterserviceversion.yaml

The controller needs to be able to retrieve PVCs directly in 2.3.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2044226

Bug 2044226: Add PVC role to controller service account

---

README.md
bundle/manifests/konveyor-forklift-operator.v99.0.0.clusterserviceversion.yaml

Require OCP v4.10 in preparation for v2.3.0

Bump minKubeVersion requirement for v2.3.0

---

roles/forkliftcontroller/defaults/main.yml

Allow the use of RELATED_IMAGE prefixed images in operator role, this is a pre-requisite for proper OSBS digest pinning. 
See references here: 
https://osbs.readthedocs.io/en/latest/users.html#pullspec-locations

Allow use of RELATED_IMAGE prefixes on FQIN role vars

---

roles/forkliftcontroller/templates/configmap-trusted-ca.yml.j2

A label should be used instead of annotations for the trusted-ca configmap , otherwise it does not get processed.

Bug 1994179: Use label instead of annotation for ca-trust cm

---

roles/forkliftcontroller/templates/configmap-trusted-ca.yml.j2

Backport: Use label instead of annotation for ca-trust cm

---

.github/workflows/ansible-lint.yml

These are causing CI jobs to fail

Remove targets from ansible linter workflows

---

roles/forkliftcontroller/defaults/main.yml
roles/forkliftcontroller/templates/deployment-ui.yml.j2

- Location of NODE_EXTRA_CA_CERTS should not be static

UI: Parametize NODE_EXTRA_CA_CERTS

---

Dockerfile

- Refresh to bring in latest changes and address current CVEs
- Tested on OCP v4.10

Refresh ansible-operator-sdk to v1.21

---

roles/forkliftcontroller/templates/deployment-controller.yml.j2

The main controller does not need to have `AUTH_REQUIRED` but the inventory does.

Move AUTH_REQUIRED from main to inventory container
