konveyor/forklift-operator

- README.md
- deploy/crds/virt.konveyor.io_virtcontrollers_crd.yaml
- deploy/olm-catalog/virt-operator/latest/konveyor-virt-operator.v99.0.0.clusterserviceversion.yaml
- deploy/olm-catalog/virt-operator/latest/virt_controller_crd.yml
- deploy/olm-catalog/virt-operator/latest/virt_provider_crd.yaml
- molecule/cluster/destroy.yml
- molecule/cluster/prepare.yml
- roles/virtcontroller/files/virt_v1alpha1_provider.yaml
- roles/virtcontroller/tasks/main.yml
- Sync virt-controller provider CRD with virt-operator
- Add alm examples on CSV file for all CRDs
> Sync virt-controller provider CRDs

- README.md
- build/Dockerfile
- deploy/olm-catalog/virt-operator/latest/konveyor-virt-operator.v99.0.0.clusterserviceversion.yaml
- deploy/olm-catalog/virt-operator/latest/virt_host.yaml
- deploy/olm-catalog/virt-operator/latest/virt_map.yaml
- deploy/olm-catalog/virt-operator/latest/virt_migration_crd.yaml
- deploy/olm-catalog/virt-operator/latest/virt_provider_crd.yaml
- roles/virtcontroller/files/virt_v1alpha1_host.yaml
- roles/virtcontroller/files/virt_v1alpha1_map.yaml
- roles/virtcontroller/files/virt_v1alpha1_migration.yaml
- roles/virtcontroller/files/virt_v1alpha1_provider.yaml
- roles/virtcontroller/tasks/main.yml
- roles/virtcontroller/templates/virt_controller_rbac.yml.j2
- Updated all CRDs against virt-controller latest
- Virt-operator and virt-controller images rebuilt
- Pinned operator sdk to v0.18.2
- Updated RBAC accordingly and pushed new OLM metadata
> Sync CRDS with virt-controller

- deploy/olm-catalog/virt-operator/latest/konveyor-virt-operator.v99.0.0.clusterserviceversion.yaml
- deploy/olm-catalog/virt-operator/latest/virt_v1alpha1_networkmap.yaml
- deploy/olm-catalog/virt-operator/latest/virt_v1alpha1_plan.yaml
- deploy/olm-catalog/virt-operator/latest/virt_v1alpha1_storagemap.yaml
- roles/virtcontroller/files/virt_v1alpha1_migration.yaml
- roles/virtcontroller/files/virt_v1alpha1_networkmap.yaml
- roles/virtcontroller/files/virt_v1alpha1_plan.yaml
- roles/virtcontroller/files/virt_v1alpha1_storagemap.yaml
- roles/virtcontroller/tasks/main.yml
- roles/virtcontroller/templates/provider.yml.j2
- Sync CRDs and handle storage and network map splits
- Create empty host provider
- Rebuilt virt-operator, virt-controller images and updated OLM metadata
- Update RBAC to reflect changes
> Sync map CRDs with virt-controller

- README.md
- deploy/non-olm/latest/operator.yaml
- roles/virtcontroller/templates/virt_controller_rbac.yml.j2
- Non-OLM fixes including RBAC
> Fix non-olm deployments

- roles/virtcontroller/defaults/main.yml
Remove placeholder UI nginx image in favor of official MTV UI build on Quay
> Update UI image to upstream official

- roles/virtcontroller/templates/virt_ui.yml.j2
- roles/virtcontroller/templates/virt_ui_configmap.yml.j2
- Rectify location to virtMeta.json for META_FILE
> UI: Fix meta file location

- deploy/olm-catalog/bundle/manifests/virt_v1alpha1_host.yaml
- deploy/olm-catalog/bundle/manifests/virt_v1alpha1_plan.yaml
- roles/virtcontroller/files/virt_v1alpha1_host.yaml
- roles/virtcontroller/files/virt_v1alpha1_plan.yaml
> virt-controller: CRDs sync

- roles/virtcontroller/templates/virt_ui.yml.j2
Follow-up PR for #30 to fix the annotation of UI service.
> Fix UI service serving cert annotation

- deploy/olm-catalog/bundle/manifests/konveyor-virt-operator.v99.0.0.clusterserviceversion.yaml
* OLM metadata update to reflect related component images
> CSV: Update related images

- roles/virtcontroller/vars/main.yml
This is a follow-up of https://github.com/konveyor/virt-operator/pull/29 to update inventory URL in virtMeta.json.
> UI - Use HTTPS to call inventory

- roles/virtcontroller/vars/main.yml
Follow-up of #29 and #40 to use TCP/8443 for inventory service
> UI - Use TCP/8443 to call inventory

- README.md
- deploy/olm-catalog/bundle/manifests/konveyor-forklift-operator.v99.0.0.clusterserviceversion.yaml
- forklift-operator-bundle.yaml
- roles/forkliftcontroller/defaults/main.yml
- roles/forkliftcontroller/meta/main.yml
- roles/forkliftcontroller/tasks/main.yml
- roles/forkliftcontroller/templates/deployment-controller.yml.j2
- roles/forkliftcontroller/templates/service-inventory.yml.j2
Cleanups and fixes necessary to make the operator back functional. Tested on OCP 4.6
> Forklift role cleanup and small fixes

- deploy/crds/virt.konveyor.io_forkliftcontrollers_crd.yaml
- deploy/crds/virt.konveyor.io_v1alpha1_forkliftcontroller_cr.yaml
- deploy/olm-catalog/bundle/manifests/forklift_v1alpha1_controller.yaml
- deploy/olm-catalog/bundle/manifests/forklift_v1alpha1_host.yaml
- deploy/olm-catalog/bundle/manifests/forklift_v1alpha1_migration.yaml
- deploy/olm-catalog/bundle/manifests/forklift_v1alpha1_networkmap.yaml
- deploy/olm-catalog/bundle/manifests/forklift_v1alpha1_plan.yaml
- deploy/olm-catalog/bundle/manifests/forklift_v1alpha1_provider.yaml
- deploy/olm-catalog/bundle/manifests/forklift_v1alpha1_storagemap.yaml
- deploy/olm-catalog/bundle/manifests/konveyor-forklift-operator.v99.0.0.clusterserviceversion.yaml
- deploy/role.yaml
- molecule/cluster/destroy.yml
- molecule/cluster/prepare.yml
- molecule/cluster/verify.yml
- molecule/test-local/converge.yml
- roles/forkliftcontroller/tasks/main.yml
- roles/forkliftcontroller/templates/forkliftcontroller.yml.j2
- roles/forkliftcontroller/templates/provider-host.yml.j2
- watches.yaml
Renames all instances of virt.konveyor.io favoring the new API group naming
> Rename API group to forklift.konveyor.io

- deploy/olm-catalog/bundle/manifests/konveyor-forklift-operator.v99.0.0.clusterserviceversion.yaml
This RBAC adjustment applies to the forklift-controller cluster role , adding the "events" resource and preventing the following permission issue with the inventory container : 
```
E1202 21:28:45.414651       1 event.go:203] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"host.164d0385d2553e63", GenerateName:"", Namespace:"openshift-migration", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), …
```
> Controller: RBAC fix for inventory container

- README.md
- deploy/olm-catalog/bundle/manifests/forklift_v1alpha1_host.yaml
- deploy/olm-catalog/bundle/manifests/forklift_v1alpha1_networkmap.yaml
- deploy/olm-catalog/bundle/manifests/forklift_v1alpha1_plan.yaml
- deploy/olm-catalog/bundle/manifests/forklift_v1alpha1_storagemap.yaml
- roles/forkliftcontroller/tasks/main.yml
- roles/forkliftcontroller/templates/forkliftcontroller.yml.j2
* Sync CRDs with controller
* Remove unnecessary patching of ForkliftController CR
> Sync CRDs and minor fixes

- roles/forkliftcontroller/templates/provisioner-openshiftstorage.cephfs.csi.ceph.com.yml.j2
- roles/forkliftcontroller/templates/provisioner-openshiftstorage.rbd.csi.ceph.com.yml.j2
Adds Ceph provisioners for OCS.
> Add OCS provisioners

- roles/forkliftcontroller/templates/provisioner-openshiftstorage.cephfs.csi.ceph.com.yml.j2
- roles/forkliftcontroller/templates/provisioner-openshiftstorage.rbd.csi.ceph.com.yml.j2
> Fix type in OCS provisioner name

- roles/forkliftcontroller/templates/provisioner-openshiftstorage.cephfs.csi.ceph.com.yml.j2
- roles/forkliftcontroller/templates/provisioner-openshiftstorage.rbd.csi.ceph.com.yml.j2
> Fix typo in OCS provisioner name

- roles/forkliftcontroller/tasks/main.yml
- roles/forkliftcontroller/templates/configmap-ui.yml.j2
- roles/forkliftcontroller/templates/oauthclient-ui.yml.j2
Cherry-picking 815b827d4f0fbd08279d379edb12f5fb26a38e9b.
> Get UI FQDN from route instead of infrastructure

- deploy/olm-catalog/bundle/manifests/forklift.konveyor.io_plans.yaml
> Sync CRDs with controller

- deploy/olm-catalog/bundle/manifests/konveyor-forklift-operator.v99.0.0.clusterserviceversion.yaml
- roles/forkliftcontroller/defaults/main.yml
- roles/forkliftcontroller/tasks/main.yml
- roles/forkliftcontroller/templates/configmap-controller.yml.j2
- roles/forkliftcontroller/templates/deployment-controller.yml.j2
This PR adds the ability to turn off or on features on a forklift deployment : 
* UI deployment is now controlled with the feature_ui role variable (By default is set to true)
* Supplied ForkliftController ALM examples contains the new variable
Any new optional features should use the same framework to control deployment.
> Add ability to control deployment optional features

- deploy/olm-catalog/bundle/manifests/konveyor-forklift-operator.v99.0.0.clusterserviceversion.yaml
* Add ALM examples for feature_validation
* Fix regression on NAME for validation service introduced in #82
> Minor fixes to CSV

- bundle/manifests/konveyor-forklift-operator.v99.0.0.clusterserviceversion.yaml
Ensure forklift-controller SA can list/get/watch virtualmachines
> RBAC: fix issue with virtualmachines

- bundle/manifests/forklift.konveyor.io_forkliftcontrollers.yaml
- bundle/manifests/konveyor-forklift-operator.v99.0.0.clusterserviceversion.yaml
- config/crd/bases/forklift.konveyor.io_forkliftcontrollers.yaml
- forklift-operator-catalog.yaml
* Update OLM logo to use Konveyor forklift instead of generic Konveyor
* Reconciled all ALM examples from latest CRDs
* Added CRD validation to ForkliftController spec
These changes will help enhance the scorecard results on SDK testing.
> CSV update

- roles/forkliftcontroller/defaults/main.yml
- roles/forkliftcontroller/templates/deployment-controller.yml.j2
Picked for release-v2.0.0 , see #89
> Set policy agent url and search interval on inventory container

- docs/README.md
- docs/releases.md
- tools/cut-release.yml
- tools/push-release-metadata.yml
This PR adds necessary tooling and also documents the procedure to create new upstream versions of konveyor forklift.
> Automate and document upstream release procedure

- bundle/manifests/konveyor-forklift-operator.v2.0.0.clusterserviceversion.yaml
- roles/forkliftcontroller/defaults/main.yml
- roles/forkliftcontroller/tasks/main.yml
- roles/forkliftcontroller/templates/deployment-ui.yml.j2
Pick for release-v2.0.0 branch , see #96
> UI: Expose OCP and forklift versions

- bundle/manifests/forklift.konveyor.io_forkliftcontrollers.yaml
- config/crd/bases/forklift.konveyor.io_forkliftcontrollers.yaml
Pick for v2.0.0 release , see #99
> Fix regression in spec validation for forkliftcontrollers CRD

- bundle/manifests/forklift.konveyor.io_hooks.yaml
- bundle/manifests/forklift.konveyor.io_hosts.yaml
- bundle/manifests/forklift.konveyor.io_migrations.yaml
- bundle/manifests/forklift.konveyor.io_networkmaps.yaml
- bundle/manifests/forklift.konveyor.io_plans.yaml
- bundle/manifests/forklift.konveyor.io_providers.yaml
- bundle/manifests/forklift.konveyor.io_provisioners.yaml
- bundle/manifests/forklift.konveyor.io_storagemaps.yaml
Sync with controller, see https://github.com/konveyor/forklift-controller/pull/206 for reference.
> CRDs: Update to v1

- roles/forkliftcontroller/tasks/main.yml
- roles/forkliftcontroller/templates/configmap-controller.yml.j2
- roles/forkliftcontroller/templates/configmap-ui.yml.j2
> Operator: remove manually managed status

- README.md
Update upstream repo documentation to reflect current state of Forklift.
> Update repo documentation

- PROJECT
- bundle/manifests/forklift.konveyor.io_forkliftcontrollers.yaml
- bundle/manifests/forklift.konveyor.io_hooks.yaml
- bundle/manifests/forklift.konveyor.io_hosts.yaml
- bundle/manifests/forklift.konveyor.io_migrations.yaml
- bundle/manifests/forklift.konveyor.io_networkmaps.yaml
- bundle/manifests/forklift.konveyor.io_plans.yaml
- bundle/manifests/forklift.konveyor.io_providers.yaml
- bundle/manifests/forklift.konveyor.io_provisioners.yaml
- bundle/manifests/forklift.konveyor.io_storagemaps.yaml
- bundle/manifests/konveyor-forklift-operator.v2.0.0.clusterserviceversion.yaml
- config/crd/bases/forklift.konveyor.io_forkliftcontrollers.yaml
- config/rbac/role.yaml
- config/samples/forklift_v1beta1_forkliftcontroller.yaml
- config/samples/kustomization.yaml
- molecule/default/tasks/forkliftcontroller_test.yml
- roles/forkliftcontroller/templates/provider-host.yml.j2
- roles/forkliftcontroller/templates/provisioner-aws-ebs.yml.j2
- roles/forkliftcontroller/templates/provisioner-azure-disk.yml.j2
- roles/forkliftcontroller/templates/provisioner-azure-file.yml.j2
- roles/forkliftcontroller/templates/provisioner-cinder.yml.j2
- roles/forkliftcontroller/templates/provisioner-gce-pd.yml.j2
- roles/forkliftcontroller/templates/provisioner-hostpath-provisioner.yml.j2
- roles/forkliftcontroller/templates/provisioner-manila.yml.j2
- roles/forkliftcontroller/templates/provisioner-openshiftstorage.cephfs.csi.ceph.com.yml.j2
- roles/forkliftcontroller/templates/provisioner-openshiftstorage.rbd.csi.ceph.com.yml.j2
- roles/forkliftcontroller/templates/provisioner-rbd.yml.j2
- roles/forkliftcontroller/templates/provisioner-vsphere-volume.yml.j2
- watches.yaml
> Update CRDs to v1beta1 API version

- roles/forkliftcontroller/defaults/main.yml
- roles/forkliftcontroller/templates/deployment-controller.yml.j2
> Add logging and profiler settings to controller

- roles/forkliftcontroller/templates/deployment-controller.yml.j2
> Fix number test in Ansible template

- bundle/manifests/konveyor-forklift-operator.v2.1.0.clusterserviceversion.yaml
> CSV: Refresh categories and other minor updates

- roles/forkliftcontroller/templates/deployment-ui.yml.j2
> Bug 1977657: Set CA bundle to /opt/app-root/src/ca.crt

- bundle/manifests/forklift.konveyor.io_plans.yaml
Sync CRDs with forklift-controller
> CRDS: Sync with controller

- .github/workflows/csv-validate.yml
- Use pull_request_head_ref instead of head_ref on PR checkout
> GH action CSV fix

- .github/workflows/pr-merge.yml
Update branch to release mappings for BZ GH action
> BZ GH action update mappings

- bundle/manifests/konveyor-forklift-operator.v2.1.0.clusterserviceversion.yaml
> Bug: 1987479 RBAC fix for hooks

- roles/forkliftcontroller/defaults/main.yml
- roles/forkliftcontroller/tasks/main.yml
> Backport: Set and increase default loglevel #145

- bundle/manifests/konveyor-forklift-operator.v99.0.0.clusterserviceversion.yaml
Controller SA changes as requested by @jortel
> controller SA RBAC updates

- bundle/manifests/konveyor-forklift-operator.v2.1.0.clusterserviceversion.yaml
> Backport: controller SA RBAC updates #147

- docs/k8s.md
- forklift-k8s.yml
Simplify Forklift deployment on k8s by using a manifest, optionally the manifest can be downloaded and modified as necessary.
> Update k8s deployment documentation

- bundle/manifests/konveyor-forklift-operator.v99.0.0.clusterserviceversion.yaml
> Minor CSV updates

- roles/forkliftcontroller/defaults/main.yml
- roles/forkliftcontroller/templates/deployment-must-gather-api.yml.j2
Enable TLS on must-gather-api , necessary work has already been merged in must-gather-api repo.
> Enable must-gather-api TLS

- bundle/manifests/konveyor-forklift-operator.v99.0.0.clusterserviceversion.yaml
- Align v2.2.0 support with OCP 4.9
- Minor CSV documentation fixes
> Require minkubeversion v1.22

- bundle/manifests/forklift.konveyor.io_migrations.yaml
- bundle/manifests/forklift.konveyor.io_plans.yaml
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2012564
> Update CRDs with fix for BZ#2012564

- bundle/manifests/forklift.konveyor.io_migrations.yaml
- bundle/manifests/forklift.konveyor.io_plans.yaml
Goes with https://github.com/konveyor/forklift-controller/pull/390
> Undo Plan precopy status change

- bundle/manifests/forklift.konveyor.io_migrations.yaml
- bundle/manifests/forklift.konveyor.io_plans.yaml
- roles/forkliftcontroller/tasks/main.yml
- Picked for release-v2.2.0, see #181 and #182 for reference.
> Pick #181 and #182

- roles/forkliftcontroller/defaults/main.yml
- roles/forkliftcontroller/templates/configmap-controller.yml.j2
- roles/forkliftcontroller/templates/deployment-controller.yml.j2
> Backport: #184 Make PRECOPY_INTERVAL a managed setting in operator

- roles/forkliftcontroller/defaults/main.yml
- roles/forkliftcontroller/templates/deployment-controller.yml.j2
Backport #186 to the `release-v2.2.0` branch.
> Bug 1942651: Make the boolean controller specific

- roles/forkliftcontroller/defaults/main.yml
- roles/forkliftcontroller/templates/deployment-must-gather-api.yml.j2
> Use must-gather image environment variable in must-gather-api deployment

- roles/forkliftcontroller/templates/deployment-must-gather-api.yml.j2
> Replace DEFAULT_IMAGE with MUST_GATHER_IMAGE

- roles/forkliftcontroller/tasks/main.yml
> Bug 2026702: Do not override controller and validation service configmaps

- roles/forkliftcontroller/defaults/main.yml
- roles/forkliftcontroller/templates/deployment-controller.yml.j2
https://issues.redhat.com/browse/MTV-38
> Enable oVirt warm migration by default

- bundle/manifests/forklift.konveyor.io_providers.yaml
See also:
- https://github.com/konveyor/forklift-controller/pull/413
- https://bugzilla.redhat.com/show_bug.cgi?id=2031033
> Bug 2031033: Update Provider CRD with `settings` field.

- roles/forkliftcontroller/defaults/main.yml
> Allow use of RELATED_IMAGE prefixes on FQIN role vars

- .github/workflows/ansible-lint.yml
Address ansible linter python module issues
> Fix ansible linter GH action

- .github/workflows/ansible-lint.yml
- Exclude molecule from linting
> Linter CI fixes

- .ansible-lint
- Add warn_lists with ansible linter configuration file
> Add ansible linter configuration file

- .github/workflows/ansible-lint.yml
Switch checkout to main branch
> Fix ansible linter checkout branch

- bundle/manifests/konveyor-forklift-operator.v2.3.1.clusterserviceversion.yaml
- roles/forkliftcontroller/defaults/main.yml
- tools/cut-release.yml
- Update metadata for v2.3.1 release
> Initialize release v2.3.1

- bundle/manifests/forklift-operator.clusterserviceversion.yaml
- forklift-k8s.yaml
- roles/forkliftcontroller/defaults/main.yml
- tools/cut-release.py
- tools/push-release-metadata.py
- tools/templates/annotations.yaml.j2
- tools/templates/bundle.Dockerfile.j2
- tools/templates/clusterserviceversion.yaml.j2
- tools/templates/forklift-k8s.yaml.j2
- Initialize upstream release v2.3.2
> Bootstrap forklift v2.3.2

- Dockerfile
> Backport #225

- docs/MTV_BZ_MAP.md
> Update MTV BZ mappings

- .config/ansible-lint.yml
- .github/workflows/ansible-lint.yml
Address various linter CI issues
> Fix linter issues

- Makefile
Add DOCKER_CMD variable which can be either `podman` or `docker` depending on which is present. If both are present it will use the `podman`.
> Makefile: Add DOCKER_CMD variable

- bundle/manifests/forklift-operator.clusterserviceversion.yaml
- tools/templates/clusterserviceversion.yaml.j2
- Add specific CSV note about pre-requirement
> Bug 2100381: Document requirement of OpenShift Virtualization / Kubevirt

- bundle/manifests/forklift-operator.clusterserviceversion.yaml
- tools/templates/clusterserviceversion.yaml.j2
- See #240 for details
- https://bugzilla.redhat.com/show_bug.cgi?id=2100381
> Backport: #240

- README.md
- docs/k8s.md
- Minor updates , add health checks and other clarifications
- See #242
> Update k8s.md documentation

- bundle/manifests/forklift-operator.clusterserviceversion.yaml
- tools/templates/clusterserviceversion.yaml.j2
- Re-phrase install section of CSV for clarity
> CSV: Update installation instructions
